# torchtitan Config.toml

[job]
dump_folder = "./outputs/demo"
description = "demo-mae training"

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 10

[metrics]
log_freq = 1
enable_tensorboard = false
save_tb_folder = "tb"

[model]
size = "2B"  # "2B" or "8B"
img_size = 512  
patch_size = 8  
mask_ratio = 0.25

[optimizer]
name = "AdamW"
lr = 3e-4

[training]
batch_size = 1
warmup_steps = 100  # lr scheduler warm up
max_norm = 1.0  # grad norm clipping
steps = 5000  # number of training steps
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 1
compile = false

[experimental]
pipeline_parallel_degree = 1

[checkpoint]
enable_checkpoint = false
folder = "checkpoint"
interval_type = "steps"
interval = 1000
model_weights_only = false
export_dtype = "bfloat16"
async_mode = "async"  # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'full'  # ['none', 'selective', 'full']
selective_ac_option = 'op'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_float8_linear = false