# torchtitan Config.toml

[job]
dump_folder = "./outputs_eval/primate_8B_131k"
description = "primate-8B-131k eval"

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 10

[metrics]
log_freq = 1
enable_tensorboard = false
save_tb_folder = "tb"

[model]
name = "llama3"
flavor = "8B"
norm_type = "rmsnorm"  # layernorm / np_layernorm / rmsnorm / fused_rmsnorm

[optimizer]
name = "AdamW"
lr = 3e-4

[training]
batch_size = 8
seq_len = 131072
vocab_size = 256
warmup_steps = 1000  # lr scheduler warm up
max_norm = 1.0  # grad norm clipping
steps = 50000  # number of training steps
data_parallel_replicate_degree = 1
data_parallel_shard_degree = 32
tensor_parallel_degree = 8
compile = true
dataset = "primate"

[experimental]
pipeline_parallel_degree = 1

[checkpoint]
enable_checkpoint = true
folder = "checkpoint"
interval_type = "steps"
interval = 60000000000000
model_weights_only = false
export_dtype = "bfloat16"
async_mode = "async"  # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'full'  # ['none', 'selective', 'full']
selective_ac_option = 'op'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_float8_linear = false
